name: Telegram Bot Monitor

on:
  schedule:
    # Runs every 15 minutes
    - cron: "*/10 * * * *"
  # Allow manual triggering
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests urllib3 python-dotenv

      - name: Run bot
        env:
          # These will be set in GitHub repository secrets
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python app.py
